import type { KitGroup, KitModule } from './kit-types'

export const financialCoreModules: KitModule[] = [
  module('round-column', 'Round column', 'base', 'Fluted column with stacked torus/plinth rings and cap blocks.', [1.3, 6.2, 1.3]),
  module('square-column', 'Square column', 'base', 'Panelized square pier with bevelled base and capital courses.', [1.35, 6.1, 1.1]),
  module('paired-column', 'Paired column', 'base', 'Two fluted columns carrying a shared classical entablature.', [4.4, 5.8, 1.5]),
  module('tall-lobby-window', 'Tall lobby window', 'base', 'Tall bronze storefront window with deep limestone surround.', [3.2, 5.3, 0.9]),
  module('lobby-door', 'Lobby door', 'base', 'Bronze double door with transom, lintel, and carved stone portal.', [3.4, 5.4, 1.0]),
  module('revolving-door-bay', 'Revolving door bay', 'base', 'Curved bronze/glass revolving entry set inside stone side columns.', [4.2, 5.6, 1.4]),
  module('service-door', 'Service door', 'base', 'Narrow black-metal service door with transom grille and stone jambs.', [2.8, 4.8, 0.9]),
  module('loading-dock-bay', 'Loading dock bay', 'base', 'Roll-up loading shutter with heavy industrial lintel and side bollards.', [4.2, 4.9, 1.0]),
  module('granite-plinth', 'Granite plinth', 'base', 'Dark granite foundation block with limestone upper cap.', [3.2, 1.15, 0.7]),
  module('corner-entrance', 'Corner entrance', 'base', 'Wrapped corner portal with two street-facing bronze doors.', [4.4, 5.6, 1.6]),
  module('colossal-column', 'Colossal column', 'base', 'Ten-meter fluted entry-order column with separate plinth, shaft, and ionic capital.', [1.7, 10.4, 1.7]),
  module('square-corner-pylon', 'Square corner pylon', 'base', 'Massive square portico end pylon paired with a round column order.', [1.8, 10.2, 1.5]),
  module('triangular-pediment', 'Triangular pediment', 'base', 'Full-depth temple-bank pediment with raking cornice and tympanum face.', [10.0, 3.0, 1.5]),
  module('pediment-eagle', 'Pediment eagle/seal', 'base', 'Raised institutional eagle and shield relief for pediment centers.', [2.2, 1.1, 0.35]),
  module('acroterion-scroll', 'Acroterion scroll', 'base', 'Corner scroll ornament for pediment and parapet ends.', [0.9, 1.0, 0.45]),
  module('company-frieze', 'Company frieze', 'base', 'Long carved company-name frieze tablet below a bank pediment.', [8.0, 0.9, 0.45]),
  module('clock-medallion', 'Clock medallion', 'base', 'Large round clock/medallion centerpiece with stone surround.', [2.0, 2.0, 0.45]),
  module('rusticated-base-block', 'Rusticated base block', 'base', 'Deep rusticated stone block with horizontal courses for fortress bases.', [3.2, 2.4, 0.9]),
  module('bank-grille', 'Bank grille', 'base', 'Large barred banking hall grille set into a heavy stone surround.', [3.4, 4.4, 0.9]),
  module('barred-window', 'Metal-barred window', 'base', 'Small secure ground-floor window with bronze/black security bars.', [2.6, 2.8, 0.72]),
  module('storefront-curtain-wall', 'Storefront curtain wall', 'base', 'Tall black bronze/glass wall set behind a column portico.', [4.6, 7.0, 0.7]),
  module('security-door', 'Security door', 'base', 'Heavy institutional security door with grille transom and side stone reveals.', [2.8, 4.4, 0.9]),
  module('wall-plaque', 'Wall plaque', 'base', 'Mounted bronze/stone bank plaque integrated into the facade.', [1.2, 1.4, 0.22]),
  module('address-plaque', 'Address plaque', 'base', 'Small address number plaque with raised bronze numerals.', [0.9, 0.55, 0.18]),
  module('flag-mount', 'Flag/banner mount', 'base', 'Angled flag/banner bracket mounted to stone facade.', [1.4, 1.6, 0.5]),
  module('bollard', 'Bollard', 'base', 'Short black street bollard for bank frontage security.', [0.45, 1.1, 0.45]),
  module('wall-camera', 'Wall camera', 'base', 'Small security camera pod and wall arm.', [0.55, 0.45, 0.7]),
  module('wall-lamp', 'Wall lamp', 'base', 'Classical wall lamp with bracket and glass globe.', [0.55, 1.4, 0.6]),
  module('sidewalk-entry', 'Sidewalk plinth/entry', 'base', 'Stone sidewalk threshold with curb, stair lip, and door landing.', [4.2, 0.45, 1.4]),
  module('window-3m', '3m window bay', 'shaft', 'Narrow office bay with bronze sash, sill, spandrel, and pilaster sides.', [3.0, 3.35, 0.72]),
  module('window-4m', '4m window bay', 'shaft', 'Wide office bay with paired vertical bronze sash and carved spandrel.', [4.0, 3.35, 0.74]),
  module('double-window-bay', 'Double-window bay', 'shaft', 'Twin office windows divided by a central stone mullion and rosette spandrels.', [4.2, 3.35, 0.78]),
  module('blank-bay', 'Blank bay', 'shaft', 'Stone service bay with framed slab panels and vertical reveal grooves.', [3.2, 3.35, 0.5]),
  module('corner-bay', 'Corner bay', 'shaft', 'Wrapped corner bay with return-facing window and shared corner pilaster.', [3.2, 3.35, 1.2]),
  module('vertical-pilaster-strip', 'Vertical pilaster strip', 'shaft', 'Reusable fluted pilaster with base block, cap, and inset channels.', [0.72, 3.35, 0.52]),
  module('spandrel-panel', 'Spandrel panel', 'shaft', 'Carved floral medallion panel for between-window courses.', [3.4, 1.0, 0.42]),
  module('floor-band-strip', 'Floor-band strip', 'shaft', 'Greek-key floor divider band with cap and base fillets.', [4.0, 0.58, 0.42]),
  module('central-glass-shaft', 'Central glass shaft', 'shaft', 'Multi-floor recessed black-glass vertical slot framed by stone piers.', [5.6, 13.4, 1.0]),
  module('solid-side-pier', 'Solid side pier', 'shaft', 'Tall blank structural pier flanking a central vertical shaft.', [1.4, 13.4, 0.86]),
  module('buttress-pier', 'Buttress pier', 'shaft', 'Projecting multi-floor buttress pier with stepped cap blocks.', [1.1, 10.0, 1.0]),
  module('pilaster-bundle', 'Pilaster bundle', 'shaft', 'Grouped vertical pilasters spanning multiple floors.', [1.2, 10.0, 0.74]),
  module('recessed-window-slot', 'Recessed window slot', 'shaft', 'Deep continuous vertical window slot with narrow stacked panes.', [2.2, 10.0, 0.95]),
  module('arched-window-bay', 'Arched window bay', 'shaft', 'Arched stone window bay with voussoirs and bronze sash.', [3.2, 4.0, 0.85]),
  module('arcade-bay', 'Romanesque arcade bay', 'shaft', 'Tall arched arcade bay with cylindrical colonnettes and deep reveal.', [3.6, 5.2, 1.1]),
  module('brick-window-bay', 'Terra-cotta window bay', 'shaft', 'Red masonry/terra-cotta bay with black sash and brick coursing.', [3.2, 3.35, 0.7]),
  module('deep-window-well', 'Deep window well', 'shaft', 'Deeply recessed window surround with stepped sill/lintel hierarchy.', [3.2, 3.35, 1.0]),
  module('carved-spandrel-vine', 'Carved vine spandrel', 'shaft', 'Decorative carved spandrel panel with vine/leaf relief.', [3.4, 1.0, 0.42]),
  module('wrapped-corner-pier', 'Wrapped corner pier', 'shaft', 'Structural corner pier wrapping both facade directions without stretching.', [1.2, 10.0, 1.2]),
  module('rounded-corner-pier', 'Rounded corner pier', 'shaft', 'Rounded/chamfered structural corner pier for Chicago financial tower corners.', [1.4, 10.0, 1.35]),
  module('structural-blank-wall', 'Structural blank wall', 'shaft', 'Tall blank wall zone for party walls, service cores, and side facades.', [3.2, 10.0, 0.62]),
  module('belt-course-small', 'Belt course small', 'trim', 'Slim belt course with bevelled upper/lower beads.', [4.0, 0.34, 0.42]),
  module('belt-course-large', 'Belt course large', 'trim', 'Large ornamented belt course with dentils and carved frieze panels.', [4.0, 0.72, 0.62]),
  module('window-sill-strip', 'Window sill strip', 'trim', 'Projecting sill strip with underside drip return.', [3.4, 0.28, 0.5]),
  module('lintel-strip', 'Lintel strip', 'trim', 'Horizontal lintel strip with panel seams and raised edge fillets.', [3.4, 0.38, 0.48]),
  module('small-cornice', 'Small cornice', 'trim', 'Short projecting cornice with dentil underside.', [4.0, 0.72, 0.85]),
  module('large-cornice', 'Large cornice', 'trim', 'Deep classical cornice with bracket blocks and carved frieze.', [4.6, 1.1, 1.1]),
  module('corner-cornice', 'Corner cornice', 'trim', 'L-shaped cornice section wrapping around a building corner.', [4.2, 1.1, 1.4]),
  module('belt-corner-joint', 'Belt corner joint', 'trim', 'Authored L/corner connector for horizontal belt and sill courses.', [1.3, 0.52, 1.3]),
  module('cornice-corner-joint', 'Cornice corner joint', 'trim', 'Heavy projecting corner block that joins cornice runs without open slab ends.', [1.6, 0.95, 1.6]),
  module('dentil-corbel-course', 'Dentil corbel course', 'trim', 'Course-aligned dentil/corbel band with bracket rhythm.', [4.0, 0.95, 0.9]),
  module('crown-window-bay', 'Crown window bay', 'crown', 'Short attic/crown bay with heavy pilasters and parapet rail blocks.', [3.6, 3.0, 0.85]),
  module('parapet-section', 'Parapet section', 'crown', 'Ornamented parapet wall with raised piers and inset panels.', [4.0, 2.0, 0.72]),
  module('corner-parapet', 'Corner parapet', 'crown', 'L-shaped parapet corner with cap blocks and round finial bases.', [3.6, 2.1, 1.2]),
  module('attic-crest-panel', 'Attic crest panel', 'crown', 'Raised top crest with small rosette tablets and a projecting cap course.', [4.0, 1.0, 0.82]),
  module('crown-pediment', 'Crown pediment', 'crown', 'Stepped central pediment block for bank tower crowns.', [4.8, 1.45, 1.0]),
  module('corner-finial', 'Corner finial', 'crown', 'Small limestone urn/obelisk finial for parapet corners.', [0.8, 1.6, 0.8]),
  module('crown-urn-finial', 'Crown urn finial', 'crown', 'Rounded classical urn finial for dense crown decoration rhythms.', [0.9, 1.4, 0.9]),
  module('crown-obelisk-finial', 'Crown obelisk finial', 'crown', 'Tall stepped obelisk finial for skyline crown silhouettes.', [0.85, 2.2, 0.85]),
  module('crown-pillar-finial', 'Crown pillar finial', 'crown', 'Small repeated parapet pillar/mini-pylon for edge finial rhythms.', [0.7, 1.2, 0.7]),
  module('crown-cartouche-panel', 'Crown cartouche panel', 'crown', 'Raised cartouche/parapet relief panel used as a crown decoration module.', [3.0, 1.25, 0.74]),
  module('sloped-metal-roof', 'Sloped metal roof', 'roof', 'Pyramidal/hipped standing-seam metal roof with ribs, hips, and ridge cap.', [10.0, 4.0, 10.0]),
  module('roof-statue-mast', 'Roof statue mast', 'roof', 'Board-of-trade style roof sculpture mast on a stone/metal pedestal.', [1.6, 5.8, 1.6]),
  module('roof-lantern', 'Roof lantern', 'roof', 'Open steel lantern/platform frame below a sculpture mast.', [2.4, 1.8, 2.4]),
  module('roof-crest', 'Roof crest', 'roof', 'Ornamental roof crest/flagpole base for skyline silhouettes.', [1.4, 2.4, 1.4]),
  module('roof-mech-box', 'Roof mech box', 'roof', 'Panelized rooftop mechanical box with vent grilles and cap slab.', [3.6, 2.0, 2.8]),
  module('hvac-cluster', 'HVAC cluster', 'roof', 'Grouped cylindrical fans and rectangular condenser boxes.', [4.2, 2.1, 2.8]),
  module('roof-railing', 'Roof railing', 'roof', 'Bronze roof safety railing with posts and horizontal bars.', [4.4, 1.15, 0.42]),
  module('antenna', 'Antenna', 'roof', 'Stacked mast antenna with collars and small equipment nodes.', [0.8, 4.8, 0.8]),
]

export const kitGroups: KitGroup[] = ['base', 'shaft', 'trim', 'crown', 'roof']

function module(
  id: KitModule['id'],
  label: string,
  group: KitGroup,
  description: string,
  size: [number, number, number]
): KitModule {
  return {
    id,
    label,
    group,
    description,
    implemented: true,
    quality: 'kit-ready',
    defaultSize: { width: size[0], height: size[1], depth: size[2] },
  }
}
