import { proxy } from 'valtio'
import type { BuildingSettings } from '../kit/kit-types'

export const buildingState = proxy<BuildingSettings>({
  seed: 1042,
  variant: 'setback-tower',
  widthBays: 9,
  depthBays: 7,
  floors: 17,
  podiumFloors: 3,
  setbackFloors: 2,
  towerScale: 0.82,
  ornamentDensity: 0.72,
  colonnade: true,
  cornerEntrance: true,
  crown: true,
  materialVariant: 'light-limestone',
  debugMode: 'beauty',
  activeTab: 'building',
  selectedModuleId: 'round-column',
  podiumStyle: 'colonnade',
  entranceType: 'center-revolving',
  shaftRhythm: 'chicago-grid',
  crownStyle: 'windowed-crown',
  roofEquipmentDensity: 0.7,
  massingPattern: 'single-tower',
  footprintStyle: 'rectangle',
  secondaryFootprintStyle: 'rectangle',
  footprintHeightMode: 'full-height',
  hardInsetSide: 'none',
  hardInsetAmount: 0,
  innerCourtWidth: 0.38,
  innerCourtDepth: 0.42,
  innerCourtOffsetX: 0,
  innerCourtOffsetZ: 0,
  skybridgeEnabled: true,
  skybridgeFloor: 8,
  buildingArchetype: 'board-of-trade-tower',
  roofStyle: 'statue-tower',
  porticoProjection: 1.8,
  centralAxisBays: 3,
  cornerTreatment: 'rounded-piers',
  crownDecorationStyle: 'classical',
  crownDecorationDensity: 0.6,
  crownFinialRhythm: 'edge-regular',
  crownFinialDensity: 0.55,
})
