import type { KitModuleRuntime } from '../shared/module-api'
import { roundColumnModule, squareColumnModule, pairedColumnModule } from './columns'
import { cornerEntranceModule, lobbyDoorModule, revolvingDoorBayModule, tallLobbyWindowModule } from './entries'
import {
  acroterionScrollModule,
  addressPlaqueModule,
  bankGrilleModule,
  barredWindowModule,
  bollardModule,
  clockMedallionModule,
  colossalColumnModule,
  companyFriezeModule,
  flagMountModule,
  pedimentEagleModule,
  rusticatedBaseBlockModule,
  securityDoorModule,
  sidewalkEntryModule,
  squareCornerPylonModule,
  storefrontCurtainWallModule,
  triangularPedimentModule,
  wallCameraModule,
  wallLampModule,
  wallPlaqueModule,
} from './institutional'
import { granitePlinthModule, loadingDockBayModule, serviceDoorModule } from './service'

export const baseModuleRuntimes: KitModuleRuntime[] = [
  { id: 'round-column', builder: roundColumnModule, slots: ['limestone'] },
  { id: 'square-column', builder: squareColumnModule, slots: ['limestone'] },
  { id: 'paired-column', builder: pairedColumnModule, slots: ['limestone', 'granite', 'bronze'] },
  { id: 'tall-lobby-window', builder: tallLobbyWindowModule, slots: ['limestone', 'glass', 'bronze', 'ornament'] },
  { id: 'lobby-door', builder: lobbyDoorModule, slots: ['limestone', 'glass', 'bronze', 'ornament'] },
  { id: 'revolving-door-bay', builder: revolvingDoorBayModule, slots: ['limestone', 'glass', 'bronze', 'ornament'] },
  { id: 'service-door', builder: serviceDoorModule, slots: ['limestone', 'glass', 'bronze', 'black-metal'] },
  { id: 'loading-dock-bay', builder: loadingDockBayModule, slots: ['limestone', 'bronze', 'black-metal'] },
  { id: 'granite-plinth', builder: granitePlinthModule, slots: ['granite', 'limestone'] },
  { id: 'corner-entrance', builder: cornerEntranceModule, slots: ['limestone', 'glass', 'bronze', 'ornament'] },
  { id: 'colossal-column', builder: colossalColumnModule, slots: ['limestone', 'granite', 'ornament'] },
  { id: 'square-corner-pylon', builder: squareCornerPylonModule, slots: ['limestone'] },
  { id: 'triangular-pediment', builder: triangularPedimentModule, slots: ['limestone', 'ornament'] },
  { id: 'pediment-eagle', builder: pedimentEagleModule, slots: ['ornament'] },
  { id: 'acroterion-scroll', builder: acroterionScrollModule, slots: ['limestone', 'ornament'] },
  { id: 'company-frieze', builder: companyFriezeModule, slots: ['limestone', 'ornament'] },
  { id: 'clock-medallion', builder: clockMedallionModule, slots: ['limestone', 'bronze', 'black-metal', 'ornament'] },
  { id: 'rusticated-base-block', builder: rusticatedBaseBlockModule, slots: ['limestone'] },
  { id: 'bank-grille', builder: bankGrilleModule, slots: ['limestone', 'glass', 'bronze', 'black-metal', 'ornament'] },
  { id: 'barred-window', builder: barredWindowModule, slots: ['limestone', 'glass', 'bronze', 'black-metal', 'ornament'] },
  { id: 'storefront-curtain-wall', builder: storefrontCurtainWallModule, slots: ['glass', 'black-metal', 'bronze'] },
  { id: 'security-door', builder: securityDoorModule, slots: ['limestone', 'black-metal', 'bronze'] },
  { id: 'wall-plaque', builder: wallPlaqueModule, slots: ['bronze'] },
  { id: 'address-plaque', builder: addressPlaqueModule, slots: ['bronze', 'black-metal'] },
  { id: 'flag-mount', builder: flagMountModule, slots: ['bronze', 'ornament'] },
  { id: 'bollard', builder: bollardModule, slots: ['black-metal', 'bronze'] },
  { id: 'wall-camera', builder: wallCameraModule, slots: ['black-metal'] },
  { id: 'wall-lamp', builder: wallLampModule, slots: ['bronze', 'glass'] },
  { id: 'sidewalk-entry', builder: sidewalkEntryModule, slots: ['granite', 'limestone'] },
]
